### ISSUE TITLE
Warehouse.sdf world physics restricting 2d lidars

### ISSUE THREAD

**Issue by bartoszOlewinski** [clearpathrobotics/clearpath_simulator#16]
**Please provide the following information:**
 - OS: Ubuntu 22.04
 - ROS 2 Distro: Humble
 - Built from source or installed: Built from source
 - Package version: 3d4f8e95a8220ff3e9231ca1436eab8e3d8d6d53, the latest 

 **Expected behaviour**
When the simulation is run with a properly setup robot.yaml file, the Lidars should be sending rays up to certain number, returning Ranges varying in size depending on what was hit.

 **Actual behaviour**
The lidar's scan topic is returning only Ranges equal to 0.0. Lidar visualization tool will showcase only extremely short rays being sent out, with occasional one ray escaping. The bug prevents use of either of two supported 2d lidars.

**To Reproduce**
Provide the steps to reproduce:
1. Fresh install of ROS2 Humble
2. Following tutorial steps to carry out simulation provided on the website: https://docs.clearpathrobotics.com/docs/ros/tutorials/simulator/install/
3. Set up the Husky A200 with either one of supported 2d lidars
4. Launch the simulation with the default world - the warehouse
5. Turn on 'Lidar Visualization tool'
6. Optionally can run echo on the scan topic, or use built-in tool to view the messages and see it sending 0.0 ranges.

**Other notes**
I have changed the render engine tag in the warehouse.sdf file from:
"ogre" to "ogre2"
That has fixed the issue on my machine.

**Comment by arthurgomes4** [comment]
yes you're right, changing line 12 of [warehouse.sdf](https://github.com/clearpathrobotics/clearpath_simulator/blob/main/clearpath_gz/worlds/warehouse.sdf) to use ogre2 with: `<render_engine>ogre2</render_engine>` fixes this issue. Although I've noticed that in its original state, the lidar visualization tool in fortress occasionally works erratically.
