### ISSUE TITLE
Qt_5.15 not found

### ISSUE THREAD

**Issue by aarontan-git** [clearpathrobotics/clearpath_simulator#32]
**Please provide the following information:**
 - OS: Ubuntu 22
 - ROS 2 Distro: Humble
 - Built from source or installed: source
 - Package version: [1e561fc](https://github.com/clearpathrobotics/clearpath_simulator/commit/1e561fc063062b55d27f260bf7c8c4d6f20e5971)

 **Expected behaviour**
I want to launch the gazebo simulator.

 **Actual behaviour**
I get an error message like the following:

`
[INFO] [launch]: All log files can be found below /home/asblab/.ros/log/2024-04-29-09-30-22-265110-asblab-3792202
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ruby $(which ign) gazebo-1]: process started with pid [3792206]
[INFO] [parameter_bridge-2]: process started with pid [3792208]
[INFO] [generate_description-3]: process started with pid [3792211]
[parameter_bridge-2] [INFO] [1714397422.446015031] [clock_bridge]: Creating GZ->ROS Bridge: [/clock (ignition.msgs.Clock) -> /clock (rosgraph_msgs/msg/Clock)] (Lazy 0)
[generate_description-3] Generated /home/asblab/aaron/clearpathrobot.urdf.xacro
[INFO] [generate_description-3]: process has finished cleanly [pid 3792211]
[INFO] [generate_launch-4]: process started with pid [3792229]
[ruby $(which ign) gazebo-1] Library error for [/usr/lib/x86_64-linux-gnu/libignition-gazebo6-ign.so.6.16.0]: /home/asblab/CoppeliaSim_Edu_V4_1_0_Ubuntu20_04/libQt5Core.so.5: version `Qt_5.15' not found (required by /usr/lib/x86_64-linux-gnu/libignition-gazebo6-ign.so.6.16.0)
[ERROR] [ruby $(which ign) gazebo-1]: process has died [pid 3792206, exit code 255, cmd 'ruby $(which ign) gazebo my_world.sdf -v 4 --gui-config /opt/ros/humble/share/clearpath_gz/config/gui.config --force-version 6'].
[INFO] [launch]: process[ruby $(which ign) gazebo-1] was required: shutting down launched system
[INFO] [generate_launch-4]: sending signal 'SIGINT' to process[generate_launch-4]
[INFO] [parameter_bridge-2]: sending signal 'SIGINT' to process[parameter_bridge-2]
[generate_launch-4] Traceback (most recent call last):
[generate_launch-4]   File "/opt/ros/humble/lib/clearpath_generator_gz/generate_launch", line 35, in <module>
[generate_launch-4]     from clearpath_generator_common.common import BaseGenerator
[generate_launch-4]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/clearpath_generator_common/common.py", line 38, in <module>
[generate_launch-4]     from clearpath_config.common.utils.yaml import read_yaml
[generate_launch-4]   File "/opt/ros/humble/lib/python3.10/site-packages/clearpath_config/common/utils/yaml.py", line 29, in <module>
[generate_launch-4]     import yaml
[generate_launch-4]   File "/home/asblab/miniconda3/lib/python3.10/site-packages/yaml/__init__.py", line 8, in <module>
[generate_launch-4]     from .loader import *
[generate_launch-4]   File "/home/asblab/miniconda3/lib/python3.10/site-packages/yaml/loader.py", line 4, in <module>
[generate_launch-4]     from .reader import *
[generate_launch-4]   File "/home/asblab/miniconda3/lib/python3.10/site-packages/yaml/reader.py", line 45, in <module>
[generate_launch-4]     class Reader(object):
[generate_launch-4]   File "/home/asblab/miniconda3/lib/python3.10/site-packages/yaml/reader.py", line 137, in Reader
[generate_launch-4]     NON_PRINTABLE = re.compile('[^\x09\x0A\x0D\x20-\x7E\x85\xA0-\uD7FF\uE000-\uFFFD\U00010000-\U0010ffff]')
[generate_launch-4]   File "/home/asblab/miniconda3/lib/python3.10/re.py", line 251, in compile
[parameter_bridge-2] [INFO] [1714397422.473243192] [rclcpp]: signal_handler(signum=2)
[generate_launch-4]     return _compile(pattern, flags)
[generate_launch-4]   File "/home/asblab/miniconda3/lib/python3.10/re.py", line 303, in _compile
[generate_launch-4]     p = sre_compile.compile(pattern, flags)
[generate_launch-4]   File "/home/asblab/miniconda3/lib/python3.10/sre_compile.py", line 792, in compile
[generate_launch-4]     code = _code(p, flags)
[generate_launch-4]   File "/home/asblab/miniconda3/lib/python3.10/sre_compile.py", line 628, in _code
[generate_launch-4]     _compile_info(code, p, flags)
[generate_launch-4]   File "/home/asblab/miniconda3/lib/python3.10/sre_compile.py", line 614, in _compile_info
[generate_launch-4]     charset, hascased = _optimize_charset(charset)
[generate_launch-4]   File "/home/asblab/miniconda3/lib/python3.10/sre_compile.py", line 328, in _optimize_charset
[generate_launch-4]     charmap[i] = 1
[generate_launch-4] KeyboardInterrupt
[ERROR] [generate_launch-4]: process has died [pid 3792229, exit code -2, cmd '/opt/ros/humble/lib/clearpath_generator_gz/generate_launch -s /home/asblab/aaron/clearpath --ros-args -r __node:=generate_launch'].
[INFO] [parameter_bridge-2]: process has finished cleanly [pid 3792208]
`

**To Reproduce**
Provide the steps to reproduce:
1. Followed clear path simulator instructions from [here](https://docs.clearpathrobotics.com/docs/ros/tutorials/simulator/install) and [here](https://docs.clearpathrobotics.com/docs/ros/tutorials/simulator/simulate)

**Comment by hilary-luo** [comment]
Qt is a dependency of Ignition Gazebo. Try repairing your install of Gazebo Fortress (`sudo apt update --fix-missing` and then `sudo apt install -f`)

Ensure that you are able to run gazebo independently (`ign gazebo`) before launching the clearpath simulator in order to isolate where the issues are happening. If you continue to have issues running Gazebo, I would suggest that you reach out on the Gazebo repo.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
