### ISSUE TITLE
Sim robot fails to move and console prints serialization warnings

### ISSUE THREAD

**Issue by tfpgh** [clearpathrobotics/clearpath_simulator#36]
**Requested Informaiton:**
 - OS: Ubuntu 22.04.4
 - ROS 2 Distro: Humble
 - Built from source
 - Package version: latest source (1f5d02a)

 **Expected behaviour**
Robot moves either using GUI buttons or switching to keyboard control and using keys.

 **Actual behaviour**
Robot falls when pressing play in the sim but then cannot be moved. The console also prints a ton of warnings about serialization (see below)

**To Reproduce**
Provide the steps to reproduce:
1. Follow the clearpath simulation installation docs
2. Launch the sim with `ros2 launch clearpath_gz simulation.launch.py`
3. Attempt to move the robot

**Console Log**:
Console log was too long to put in body of issue. Link here: https://hastebin.com/share/makanuziyu.makefile

**Comment by luis-camero** [comment]
@tfpgh what `robot.yaml` did you use to run the simulation? When the robot is spawned in the simulation and the simulation is started, how are you trying to move the robot? Are you setting the appropriate namespace? See the [simulator documentation](https://docs.clearpathrobotics.com/docs/ros/tutorials/simulator/simulate#driving-the-robot).
